version: '3.8'

services:
  pyroscope:
    image: grafana/pyroscope:1.20.3
    container_name: day23-pyroscope
    ports:
      - "127.0.0.1:4040:4040"
    volumes:
      - pyroscope_data:/var/lib/pyroscope

networks:
  obs:
    external: true

volumes:
  pyroscope_data:
